apiVersion: v1
kind: Template
metadata:
  name: tensorflow-release-job
  annotations:
    description: This is Thoth - tensorflow build
    openshift.io/display-name: Thoth Core
    version: 0.4.0
    tags: poc,thoth,tensorflow-release,ai-stacks
    template.openshift.io/documentation-url: https://github.com/Thoth-Station/
    template.openshift.io/long-description: >
      This template defines resources needed to deploy job for tensorflow-release-job to OpenShift.
    template.openshift.io/provider-display-name: Red Hat, Inc.
  labels:
    template: tensorflow-release-job
    app: thoth
    component: tensorflow-release

objects:
- apiVersion: batch/v1
  kind: Job
  metadata:
    name: tensorflow-release-job
    labels:
      app: thoth
      component: tensorflow-release

  spec:
    parallelism: 1    
    completions: 1    
    template:  
      spec:
        containers:
        - image: quay.io/aicoe/tensorflow-release-job:latest
          name: tensorflow-release-job
          env:
          - name: OCP_URL
            valueFrom:
              secretKeyRef:
                key: OCP_URL
                name: "${OCP_SECRET}"
          - name: OCP_NAMESPACE
            valueFrom:
              secretKeyRef:
                key: OCP_NAMESPACE
                name: "${OCP_SECRET}"
          - name: OCP_TOKEN
            valueFrom:
              secretKeyRef:
                key: OCP_TOKEN
                name: "${OCP_SECRET}"
          - name: S2I_IMAGE
            value: "${S2I_IMAGE}"
          - name: RESOURCE_LIMITS_CPU
            value: "${RESOURCE_LIMITS_CPU}"
          - name: RESOURCE_LIMITS_MEMORY
            value: "${RESOURCE_LIMITS_MEMORY}"
          - name: RESOURCE_QUOTA
            value: "${RESOURCE_QUOTA}"
          - name: QUOTA_NAME
            value: "${QUOTA_NAME}"
          - name: BAZEL_VERSION
            value: "${BAZEL_VERSION}"
          - name: CUSTOM_BUILD
            value: "${CUSTOM_BUILD}"
          - name: BUILD_OPTS
            value: "${BUILD_OPTS}"
          - name: TF_CUDA_VERSION
            value: "${TF_CUDA_VERSION}"
          - name: TF_CUDA_COMPUTE_CAPABILITIES
            value: "${TF_CUDA_COMPUTE_CAPABILITIES}"
          - name: TF_CUDNN_VERSION
            value: "${TF_CUDNN_VERSION}"
          - name: TF_NEED_OPENCL_SYCL
            value: "${TF_NEED_OPENCL_SYCL}"
          - name: TF_CUDA_CLANG
            value: "${TF_CUDA_CLANG}"
          - name: GCC_HOST_COMPILER_PATH
            value: "${GCC_HOST_COMPILER_PATH}"
          - name: CUDA_TOOLKIT_PATH
            value: "${CUDA_TOOLKIT_PATH}"
          - name: CUDNN_INSTALL_PATH
            value: "${CUDNN_INSTALL_PATH}"
          - name: TF_NEED_JEMALLOC
            value: "${TF_NEED_JEMALLOC}"
          - name: TF_NEED_GCP
            value: "${TF_NEED_GCP}"
          - name: TF_NEED_VERBS
            value: "${TF_NEED_VERBS}"
          - name: TF_NEED_HDFS
            value: "${TF_NEED_HDFS}"
          - name: TF_ENABLE_XLA
            value: "${TF_ENABLE_XLA}"
          - name: TF_NEED_OPENCL
            value: "${TF_NEED_OPENCL}"
          - name: TF_NEED_CUDA
            value: "${TF_NEED_CUDA}"
          - name: TF_NEED_MPI
            value: "${TF_NEED_MPI}"
          - name: TF_NEED_GDR
            value: "${TF_NEED_GDR}"
          - name: TF_NEED_S3
            value: "${TF_NEED_S3}"
          - name: TF_NEED_KAFKA
            value: "${TF_NEED_KAFKA}"
          - name: TF_NEED_OPENCL_SYCL
            value: "${TF_NEED_OPENCL_SYCL}"
          - name: TF_DOWNLOAD_CLANG
            value: "${TF_DOWNLOAD_CLANG}"
          - name: TF_SET_ANDROID_WORKSPACE
            value: "${TF_SET_ANDROID_WORKSPACE}"
          - name: TF_NEED_TENSORRT
            value: "${TF_NEED_TENSORRT}"
          - name: NCCL_INSTALL_PATH
            value: "${NCCL_INSTALL_PATH}"
          - name: TF_GIT_BRANCH
            value: "${TF_GIT_BRANCH}"
          - name: TEST_WHEEL_FILE
            value: "${TEST_WHEEL_FILE}"
          - name: GIT_RELEASE_REPO
            value: "${GIT_RELEASE_REPO}"
          - name: GIT_TOKEN
            value: "${SESHETA_GITHUB_ACCESS_TOKEN}"
          - name: SOURCE_REPOSITORY
            value: "${SOURCE_REPOSITORY}"
          - name: GENERIC_WEBHOOK_SECRET
            value: "${GENERIC_WEBHOOK_SECRET}" 
          - name: BUILD_MAP
            value: "${BUILD_MAP}"
          resources:
            requests:
              memory: "1Gi"
              cpu: "1"
            limits:
              memory: "1Gi"
              cpu: "1"
        restartPolicy: Never
        lookupPolicy:
          local: true
parameters:
  - name: OCP_SECRET
    description: Name of the secret config on openshift
    required: true
  - name: RESOURCE_LIMITS_CPU
    description: Resource limits for Openshft quota CPU
    value: "4"
    required: true
  - name: RESOURCE_LIMITS_MEMORY
    description: Resource limits for Openshft quota Memory
    value: "8Gi"
    required: true
  - name: RESOURCE_QUOTA
    description: If resource quota check is to be executed or not
    value: "1"
    required: false
  - name: QUOTA_NAME
    description: Name of the resource quota on openshift
    required: false
  - name: SOURCE_REPOSITORY
    description: Git repository for source.
    value: 'https://github.com/thoth-station/tensorflow-build-s2i.git'
    required: true
  - name: S2I_IMAGE
    description: "registry.fedoraproject.org/f27/s2i-core, registry.fedoraproject.org/f28/s2i-core, registry.access.redhat.com/rhscl/s2i-core-rhel7"
    value: "registry.fedoraproject.org/f27/s2i-core"
    required: true
  - name: BAZEL_VERSION
    description: BAZEL_VERSION
    value: 0.11.0
    required: true
  - name: GENERIC_WEBHOOK_SECRET
    description: A secret string used to configure the Generic webhook.
    value: tf-build-secret
    required: true
  - name: VERSION
    description: Version of the build image, i.e docker image tag
    value: latest
    required: true
  - name: CUSTOM_BUILD
    description: Set to custom BUILD command
    value: bazel build --copt=-mavx --copt=-mavx2 --copt=-mfma --copt=-mfpmath=both
      --copt=-msse4.2  --cxxopt='-D_GLIBCXX_USE_CXX11_ABI=0' --verbose_failures //tensorflow/tools/pip_package:build_pip_package
    required: false
  - name: BUILD_OPTS
    description: Custom options to bazel BUILD command
    value: ''
    required: false
  - name: TF_CUDA_VERSION
    description: TF_CUDA_VERSION depends on TF_NEED_CUDA
    value: '9.2'
    required: false
  - name: TF_CUDA_COMPUTE_CAPABILITIES
    description: TF_CUDA_COMPUTE_CAPABILITIES depends on TF_NEED_CUDA
    value: '3.0,3.5,5.2,6.0,6.1,7.0'
    required: false
  - name: TF_CUDNN_VERSION
    description: TF_CUDNN_VERSION depends on TF_NEED_CUDA
    value: '7'
    required: false
  - name: CUDA_TOOLKIT_PATH
    description: CUDA_TOOLKIT_PATH depends on TF_NEED_CUDA
    value: '/usr/local/cuda'
    required: true
  - name: CUDNN_INSTALL_PATH
    description: CUDNN_INSTALL_PATH depends on TF_NEED_CUDA
    value: '/usr/local/cuda'
    required: true
  - name: GCC_HOST_COMPILER_PATH
    description: GCC_HOST_COMPILER_PATH depends on TF_NEED_CUDA
    value: '/usr/bin/gcc'
    required: true
  - name: TF_NEED_OPENCL_SYCL
    description: TF_NEED_OPENCL_SYCL
    value: '0'
    required: true
  - name: TF_CUDA_CLANG
    description: TF_CUDA_CLANG
    value: '0'
    required: true
  - name: TF_NEED_JEMALLOC
    description: TF_NEED_JEMALLOC
    value: '1'
    required: true
  - name: TF_NEED_GCP
    description: TF_NEED_GCP
    value: '0'
    required: true
  - name: TF_NEED_VERBS
    description: TF_NEED_VERBS
    value: '0'
    required: true
  - name: TF_NEED_HDFS
    description: TF_NEED_HDFS
    value: '0'
    required: true
  - name: TF_ENABLE_XLA
    description: TF_ENABLE_XLA
    value: '0'
    required: true
  - name: TF_NEED_OPENCL
    description: TF_NEED_OPENCL
    value: '0'
    required: true
  - name: TF_NEED_CUDA
    description: TF_NEED_CUDA
    value: '0'
    required: true
  - name: TF_NEED_MPI
    description: TF_NEED_MPI
    value: '0'
    required: true
  - name: TF_NEED_GDR
    description: TF_NEED_GDR
    value: '0'
    required: true
  - name: TF_NEED_S3
    description: TF_NEED_S3
    value: '0'
    required: true
  - name: TF_NEED_KAFKA
    description: TF_NEED_KAFKA
    value: '0'
    required: true
  - name: TF_NEED_OPENCL_SYCL
    description: TF_NEED_OPENCL_SYCL
    value: '0'
    required: true
  - name: TF_DOWNLOAD_CLANG
    description: TF_DOWNLOAD_CLANG
    value: '0'
    required: true
  - name: TF_SET_ANDROID_WORKSPACE
    description: TF_SET_ANDROID_WORKSPACE
    value: '0'
    required: true
  - name: TF_NEED_TENSORRT
    description: TF_NEED_TENSORRT
    value: '0'
    required: true
  - name: NCCL_INSTALL_PATH
    description: "/usr/local/nccl-2.2"
    value: '/usr/local/nccl-2.2'
    required: true
  - name: TEST_WHEEL_FILE
    description: "(y or n)To run a simple test code to test wheel file."
    value: 'y'
    required: true
  - name: TF_GIT_BRANCH
    description: TF_GIT_BRANCH
    value: 'r1.9'
    required: true
  - name: SESHETA_GITHUB_ACCESS_TOKEN
    description: SESHETA_GITHUB_ACCESS_TOKEN value is required if you release to github
    value: ''
    required: true
  - name: GIT_RELEASE_REPO
    description: GIT_RELEASE_REPO
    value: 'https://github.com/AICoE/tensorflow-wheels.git'
    required: true
  - name : BUILD_MAP
    description: Map of all the builds that are required to be deployed
    required: true
